/**
 * WebSocket Event Name Constants
 */

export const CLIENT_EVENTS = {
  AUTH_GUEST: "AUTH_GUEST",
  CREATE_LOBBY: "CREATE_LOBBY",
  JOIN_LOBBY: "JOIN_LOBBY",
  LEAVE_LOBBY: "LEAVE_LOBBY",
  TOGGLE_READY: "TOGGLE_READY",
  START_GAME: "START_GAME",
  KICK_PLAYER: "KICK_PLAYER",
  SEND_MESSAGE: "SEND_MESSAGE",
  GET_LOBBY_LIST: "GET_LOBBY_LIST",
} as const;

export const SERVER_EVENTS = {
  CONNECTED: "CONNECTED",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  LOBBY_CREATED: "LOBBY_CREATED",
  LOBBY_JOINED: "LOBBY_JOINED",
  LOBBY_LEFT: "LOBBY_LEFT",
  PLAYER_JOINED: "PLAYER_JOINED",
  PLAYER_LEFT: "PLAYER_LEFT",
  PLAYER_READY_CHANGED: "PLAYER_READY_CHANGED",
  PLAYER_KICKED: "PLAYER_KICKED",
  GAME_STARTED: "GAME_STARTED",
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CHAT_HISTORY: "CHAT_HISTORY",
  LOBBY_LIST: "LOBBY_LIST",
  LOBBY_LIST_UPDATED: "LOBBY_LIST_UPDATED",
  KICKED: "KICKED",
  ERROR: "ERROR",
} as const;
